version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - .:/app
      - php_logs:/var/log/php
    environment:
      APP_ENV: dev
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    ports:
      - "9003:9003"
      - "8000:8000"
    depends_on:
      - redis # Ensure app waits for Redis to be ready

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authenticator
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 12345678
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    ports:
      - "8088:80"
    depends_on:
      - app

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  php_logs:
  redis_data:
